version: '3.8'

services:
  angular-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  laravel-app:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./back:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
